---
# yamllint disable rule:line-length
repo-bundle:
  el9:
    gpgcheck: true
    gpgkey: file:///usr/share/distribution-gpg-keys/alma/RPM-GPG-KEY-AlmaLinux-9
    baseurl: "{{.Host}}/artifactory/alma-vault/{{.Version}}/{{.RepoName}}/{{.Arch}}/os"
    repo:
      AppStream:
        enabled: true
      BaseOS:
        enabled: true
      CRB:
        enabled: true
      devel:
        enabled: false
    version-labels:
      default: 9.1
      # Don't use latest if you want reproducible builds, this is just for experiments
      latest: 9.2

  # epel9 is not version controlled
  epel9:
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9
    baseurl: "{{.Host}}/artifactory/centos-9-epel/{{.Arch}}/"
    repo:
      epel:
        enabled: true
