---
# yamllint disable rule:line-length
repo-bundle:
  el9:
    gpgcheck: true
    gpgkey: file:///usr/share/distribution-gpg-keys/alma/RPM-GPG-KEY-AlmaLinux-9
    baseurl: "{{.Host}}/artifactory/alma-vault/{{.Version}}/{{.RepoName}}/{{.Arch}}/os"
    repo:
      AppStream:
        enabled: true
      BaseOS:
        enabled: true
      CRB:
        enabled: true
      devel:
        enabled: false
      extras:
        enabled: false
    version-labels:
      default: 9.2
      # Don't use latest if you want reproducible builds, this is just for experiments
      latest: 9.3

  epel9-subset:
    gpgcheck: true
    gpgkey: file:///usr/share/distribution-gpg-keys/epel/RPM-GPG-KEY-EPEL-9
    baseurl: "{{.Host}}/artifactory/eext-sources/epel9-frozen-subsets/{{.Version}}/"
    repo:
      epel9:
        enabled: true
    version-labels:
      default: v20230901-1
