---
repo:
  AppStream:
    baseurl: "{{.Host}}/{{.Version}}/AppStream/{{.Arch}}/os/"
  BaseOS:
    baseurl: "{{.Host}}/{{.Version}}/BaseOS/{{.Arch}}/os/"
  CRB:
    baseurl: "{{.Host}}/{{.Version}}/CRB/{{.Arch}}/os/"
  epel:
    baseurl: "{{.Host}}/{{.Version}}/{{.Arch}}/"
