---
repo:
  AppStream:
    baseurl: "{{.Host}}/artifactory/alma-vault/{{.Version}}/AppStream/{{.Arch}}/os"

  BaseOS:
    baseurl: "{{.Host}}/artifactory/alma-vault/{{.Version}}/BaseOS/{{.Arch}}/os"

  CRB:
    baseurl: "{{.Host}}/artifactory/alma-vault/{{.Version}}/CRB/{{.Arch}}/os"

  epel:
    baseurl: "{{.Host}}/{{.Version}}/{{.Arch}}/"

version-labels:
  default: 9.1
  latest: 9.2 # Don't use this if you want reproducible builds, this is just for experiments
