---
# yamllint disable rule:line-length
repo:
  AppStream:
    baseurl: "{{.Host}}/artifactory/alma-vault/{{.Version}}/AppStream/{{.Arch}}/os"

  BaseOS:
    baseurl: "{{.Host}}/artifactory/alma-vault/{{.Version}}/BaseOS/{{.Arch}}/os"

  CRB:
    baseurl: "{{.Host}}/artifactory/alma-vault/{{.Version}}/CRB/{{.Arch}}/os"

  devel:
    baseurl: "{{.Host}}/artifactory/alma-vault/{{.Version}}/devel/{{.Arch}}/os"

  epel:
    baseurl: "{{.Host}}/{{.Version}}/{{.Arch}}/"

version-labels:
  default: 9.1
  # Don't use latest if you want reproducible builds, this is just for experiments
  latest: 9.2
