---
on:   # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - 'main'

env:
  TEST_TAG: eext:test

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v2.0.0
        with:
          # using recursive to avoid hardcoding paths
          # and missing any future additions
          recursive: true
          verbose: true
          ignore: DL3002

      - name: Lint yaml files
        run: yamllint .
